name: "StoreGate - Update version"
author: "Fried-Synapse"
description: "Update the version stored in your repo"
branding:
  icon: 'chevrons-up'
  color: 'green'
  
inputs:
  type:
    description: 'Select version update type'
    required: true
  variableName:
    description: 'Name of the variable to store the version for incremental use. Note: This will be save in your repo settings under /settings/variables/actions'
    required: false
    default: "VERSION"

outputs:
  version:
    description: 'The current version'
    value: ${{ steps.updateVersion.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Update Version
      id: updateVersion
      shell: bash
      run: |
        version=$($GITHUB_ACTION_PATH/../bin/StoreGate version \
          --update \
          --${{ inputs.type }} \
          --variable ${{ inputs.variableName }})
        echo "VERSION=$version" >> $GITHUB_ENV