#!/bin/bash

if ! git diff --cached --name-only | grep -q '^DotNet/'; then
  echo "No changes detected in DotNet. Skipping build."
  exit 0
fi

mkdir -p ./Run/bin
rm -rf ./Run/bin/*

dotnet publish DotNet/StoreGate \
  --output ./Run/bin \
  --configuration Release \
  --runtime linux-x64

git add ./Run/bin/*