name: "StoreGate"
description: "An example GitHub Action that uses a Bash script"
inputs:
  versionUpdatePart:
    description: "Which version part to increase: major/minor/patch"
    required: true
    default: "minor"
runs:
  using: "composite"
  steps:
    - name: Increase Version
      shell: bash
      run: echo ${{ env.TEST }}

    - name: Increase Version
      shell: bash
      run: bin/StoreGate version --update --${{ inputs.versionUpdatePart }}