name: "StoreGate"
description: "An example GitHub Action that uses a Bash script"
inputs:
  versionUpdatePart:
    description: 'Select version update type'
    required: true
    default: 'minor'
    type: choice
    options:
      - major
      - minor
      - patch
runs:
  using: "composite"
  steps:
    - name: Increase Version
      id: increaseVersion
      shell: bash
      run: |
        echo "version=$$(bin/StoreGate version --update --${{ inputs.versionUpdatePart }})" >> $GITHUB_OUTPUT 

    - name: Release to GitHub
      shell: bash
      run: |
        echo "The updated version is: ${{ steps.increaseVersion.outputs.version }}"