name: "StoreGate"
description: "An example GitHub Action that uses a Bash script"
inputs:
  versionUpdatePart:
    description: "Which version part to increase: Major/Minor/Patch"
    required: true
    default: "Minor"
runs:
  using: "composite"
  steps:
    - name: Simple Test
      shell: bash
      run: bin/StoreGate test -m "${{ inputs.message }}"

    - name: Simple Test 2
      shell: bash
      run: bin/StoreGate test -m "${{ inputs.message2 }}"