name: "StoreGate"
description: "An example GitHub Action that uses a Bash script"
inputs:
  versionUpdatePart:
    description: 'Select version update type'
    required: true
    default: 'minor'
    type: choice
    options:
      - major
      - minor
      - patch
runs:
  using: "composite"
  steps:
    - name: Increase Version
      shell: bash
      run: bin/StoreGate version --update --${{ inputs.versionUpdatePart }}