name: "StoreGate"
description: "An example GitHub Action that uses a Bash script"
inputs:
  versionUpdatePart:
    description: 'Select version update type'
    required: true
  releaseName:
    description: 'The name of the file to appear on GitHub'
    required: true
  releaseFile:
    description: 'File path'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set StoreGate environment variable for when we have multiple OS support
      shell: bash
      echo "storeGate=bin/StoreGate" >> $GITHUB_ENV

    - name: Increase Version
      id: increaseVersion
      shell: bash
      run: |
        echo "version=$(${{ env.storeGate }} version --update --${{ inputs.versionUpdatePart }})" >> $GITHUB_OUTPUT 

    - name: Release to GitHub
      shell: bash
      run: |
        ${{ env.storeGate }} release \
          -version ${{ steps.increaseVersion.outputs.version }} 
          -name ${{ inputs.name }} 
          -file ${{ inputs.file }} 
