name: "StoreGate"
description: "An example GitHub Action that uses a Bash script"
inputs:
  message:
    description: "The message to display"
    required: true
    default: "Hello, World!"
  message2:
    description: "The message to display"
    required: true
    default: "Hello, World!"
runs:
  using: "composite"
  steps:
    - name: Simple Test
      shell: bash
      run: bin/StoreGate test -m "${{ inputs.message }}"

    - name: Simple Test 2
      shell: bash
      run: bin/StoreGate test -m "${{ inputs.message2 }}"