name: "StoreGate"
author: "Fried-Synapse"
description: "Creates a Unity package based on the given folder"
branding:
  icon: 'package'
  color: 'green'

inputs:
  packagePath:
    description: 'Path of the folder to pack'
    required: true
  packageName:
    description: 'Name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Docker
      shell: bash
      run: |
        cp -r ${GITHUB_ACTION_PATH}/../sh/* .
        cp -r ${GITHUB_ACTION_PATH}/* .
        sed -i "s/UNITY_VERSION/${{ env.UNITY_VERSION }}/" Dockerfile
        docker build -t unity-editor .
        docker run --rm unity-editor 