name: "StoreGate"
author: "Fried-Synapse"
description: "Creates a Unity package based on the given folder"
branding:
  icon: 'package'
  color: 'green'

inputs:
  packagePath:
    description: 'Path of the folder to pack'
    required: true
  packageName:
    description: 'Name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Docker
      shell: bash
      run: |
        sed -i "s/UNITY_VERSION/${{ inputs.unity_version }}/" ${GITHUB_ACTION_PATH}/Dockerfile
        docker build -t unity-editor ${GITHUB_ACTION_PATH}/.
        docker run --rm unity-editor