name: "StoreGate"
author: "Fried-Synapse"
description: "Creates a Unity package based on the given folder"
branding:
  icon: 'package'
  color: 'green'

inputs:
  unityVersion:
    description: 'Version of Unity to use (e.g., 2023.1.0f1)'
    required: true
  unityProjectPath:
    description: 'Path to the unity project'
    required: false
    default: "."
  packagePath:
    description: 'Path of the folder to pack'
    required: true
  packageName:
    description: 'Name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Unity Package
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:${{ github.workspace }} \
          -w ${{ github.workspace }} \
          unityci/editor:${{ inputs.unityVersion }} \
          /bin/bash -c "
            # Activate Unity license using the provided credentials
            unity-editor -batchmode -quit \
              -username \"${UNITY_EMAIL}\" \
              -password \"${UNITY_PASSWORD}\" \
              -serial \"${UNITY_LICENSE}\" && \
            # Export the package
            unity-editor -batchmode -quit \
              -projectPath \"${{ inputs.unityProjectPath }}\" \
              -exportPackage \"${{ inputs.packagePath }}\" \"${{ inputs.packageName }}.unitypackage\" \
              -logFile /dev/stdout \
          "
