name: "StoreGate"
author: "Fried-Synapse"
description: "Creates a Unity package based on the given folder"
branding:
  icon: 'package'
  color: 'green'

inputs:
  unityVersion:
    description: 'Version of Unity to use (e.g., 2023.1.0f1)'
    required: true
  unityProjectPath:
    description: 'Path to the unity project'
    required: false
    default: "."
  packagePath:
    description: 'Path of the folder to pack'
    required: true
  packageName:
    description: 'Name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Extract Unity Serial from License
      if: env.UNITY_LICENSE != ''
      shell: bash
      run: |
        echo "UNITY_SERIAL=$($GITHUB_ACTION_PATH/../sh/GetSerialFromLicence.sh '${{ env.UNITY_LICENSE }}')" >> $GITHUB_ENV

    - name: Build Unity Package
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:${{ github.workspace }} \
          -w ${{ github.workspace }} \
          unityci/editor:${{ inputs.unityVersion }} \
          /bin/bash -c "
            # Activate Unity license using the provided credentials
            unity-editor -batchmode -quit \
              -username \"${{ env.UNITY_EMAIL }}\" \
              -password \"${{ env.UNITY_PASSWORD }}\" \
              -serial \"${{ env.UNITY_SERIAL }}\" \
              -logFile /dev/stdout && \
            # Export the package
            unity-editor -batchmode -quit \
              -projectPath \"${{ inputs.unityProjectPath }}\" \
              -exportPackage \"${{ inputs.packagePath }}\" \"${{ inputs.packageName }}.unitypackage\" \
              -logFile /dev/stdout"
