name: "StoreGate"
description: "Creates a unity package based on the give folder"
inputs:
  unityVersion:
    description: 'Version of Unity to use (e.g., 2023.1.0f1)'
    required: true
  path:
    description: 'Path of the folder to pack'
    required: true
  name:
    description: 'Name of the package'
    required: true
    
runs:
  using: "composite"
  container:
    image: "unityci/editor:${{ inputs.unityVersion }}"
  steps:
    - name: Build Unity Package
      run: |
        unity_path="/opt/Unity/Hub/Editor/${{ inputs.unityVersion }}/Editor/Unity"
        $unity_path -batchmode -quit -projectPath "${{ inputs.path }}" -exportPackage "${{ inputs.path }}" "${{ inputs.name }}.unitypackage"
