name: "StoreGate"
author: "Fried-Synapse"
description: "Creates a Unity package based on the given folder"
branding:
  icon: 'package'
  color: 'green'

inputs:
  unityVersion:
    description: 'Version of Unity to use (e.g., 2023.1.0f1)'
    required: true
  unityProjectPath:
    description: 'Path to the unity project'
    required: false
    default: "."
  packagePath:
    description: 'Path of the folder to pack'
    required: true
  packageName:
    description: 'Name of the package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Unity Package
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/index.sh \
          "${{ inputs.unityVersion }}" \
          "${{ inputs.unityProjectPath }}" \
          "${{ inputs.packagePath }}" \
          "${{ inputs.packageName }}"
