name: "StoreGate"
author: "Fried-Synapse"
description: "Creates a Unity package based on the given folder"
branding:
  icon: 'package'
  color: 'green'

inputs:
  projectPath:
    description: 'Path of the folder to pack'
    required: true
    default: "."
  assetsPaths:
    description: 'Path of the folder to pack'
    required: true
  packageName:
    description: 'Name of the package'
    required: true

outputs:
  version:
    description: 'The full path of the package'
    value: ${{ steps.updateVersion.outputs.packagePath }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: | 
        ${GITHUB_ACTION_PATH}/Index.sh \
          ${{inputs.projectPath}} \
          ${{inputs.assetsPaths}} \
          ${{inputs.packageName}}
        