name: "StoreGate - Release to GitHub"
description: "Releases the specified file to your repo's releases page."
inputs:
  version:
    description: 'The version of the release'
    required: true
  name:
    description: 'The name of the file to appear on GitHub'
    required: true
  file:
    description: 'File path'
    required: true
runs:
  using: "composite"
  steps:
    - name: Release to GitHub
      shell: bash
      run: |
        bin/StoreGate release-gh \
          -version ${{ inputs.version }} \
          -name ${{ inputs.name }} \
          -file ${{ inputs.file }} 
