name: "StoreGate - Release to GitHub"
author: "Fried-Synapse"
description: "Releases the specified file to your repo's releases page."
branding:
  icon: 'share'
  color: 'gray-dark'

inputs:
  version:
    description: 'The version of the release'
    required: true
  name:
    description: 'The name of the file to appear on GitHub'
    required: true
  file:
    description: 'File path'
    required: true
runs:
  using: "composite"
  steps:
    - name: Release to GitHub
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/../bin/StoreGate release-gh \
          -version ${{ inputs.version }} \
          -name ${{ inputs.name }} \
          -file ${{ inputs.file }} 
