name: "Release"

on:
  workflow_dispatch:
    inputs:
      versionUpdatePart:
        description: 'Select version update type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: UpdateVersion
        id: updateVersion
        uses: Fried-Synapse/StoreGate/Run/UpdateVersion@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          type: ${{ github.event.inputs.versionUpdatePart }}

      - name: Create Package
        id: createPackage
        uses: Fried-Synapse/StoreGate/Run/CreateUnityPackage@main
        env:
          UNITY_VERSION: "ubuntu-2022.3.39f1-android-3"
          UNITY_LICENCE: ${{ secrets.UNITY_LICENCE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: "Unity"
          packagePath: Assets/StoreGate
          packageName: StoreGate
    
      # - name: ReleaseGitHub
      #   uses: Fried-Synapse/StoreGate/Run/ReleaseGitHub@main
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   with:
      #     version: ${{ steps.updateVersion.outputs.version }}
      #     name: ${{ steps.createPackage.outputs.packageName }}
      #     file: ./Unity/Assets/StoreGate/Success.txt