name: "Release"

on:
  workflow_dispatch:
    inputs:
      versionUpdatePart:
        description: 'Select version update type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: UpdateVersion
      id: updateVersion
      uses: Fried-Synapse/StoreGate/Run/UpdateVersion@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        updatePart: ${{ github.event.inputs.versionUpdatePart }}
        variableName: "Release Version"

    - name: ReleaseGitHub
      uses: Fried-Synapse/StoreGate/Run/ReleaseGitHub@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        version: steps.updateVersion.outputs.version
        name: StoreGate.txt
        file: ./Unity/Assets/StoreGate/Success.txt