name: "Release"

on:
  workflow_dispatch:
    inputs:
      versionUpdatePart:
        description: 'Select version update type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Release
      uses: Fried-Synapse/StoreGate@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        versionUpdatePart: ${{ github.event.inputs.versionUpdatePart }}
        release:
          name: StoreGate.txt
          file: ./Unity/Assets/StoreGate/Success.txt